apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubetag-cluster-role-binding
subjects:
 - kind: ServiceAccount
   name: kubetag-controller-sa
   namespace: default
roleRef:
  kind: ClusterRole
  name: kubetag-cluster-role
  apiGroup: rbac.authorization.k8s.io
