name: Image-Registry-Publish

on:
  workflow_run:
    workflows: ["Go Unit Tests"]
    types:
    - completed

jobs:
  release:
    if: ${{ github.event.worfklow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to GHCR
          run : echo "${{ secrets.IMAGE_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: Get tag name
          id: get_tag
          run: | 
             git fetch --tags
             TAG=$(git tag --points-at ${{ github.event.workflow_run.head_sha }})
             echo "TAG=$TAG" >> $GITHUB_ENV

        - name: Build and push Docker image to ghcr.io
          run: | 
                docker build -t ghcr.io/orenr2301/kubetag:${{ github.ref_name}} .
                docker push ghcr.io/orenr2301/kubetag:${{ github.ref_name}}

        - name: Set up Helm
          uses: azure/helm@v4

        - name: Package Helm chart
          run: helm package chart/kubetag

        - name: Push Helm chart to GHCR
          run: |
                helm registry login ghcr.io -u ${{ github.actor }} --password ${{ secrets.IMAGE_TOKEN }}
                helm push kubetag-*.tgz oci://ghcr.io/orenr2301/charts