# Run tests
unit-test: fmt vet 
  go test ./pkg/... -coverprofile cover.out 
integration-test: fmt vet 
  go test ./controllers/... -coverprofile cover.out
# Run go fmt against code
fmt: 
  go fmt ./... 
# Run go vet against code
vet: 
  go vet ./...